parameters:
    my_user_provider.class: Malkos\UserBundle\Security\FOSUBUserProvider
 
services:
    my_user_provider:
        class: "%my_user_provider.class%"
        arguments: [@fos_user.user_manager,{facebook: facebook_id, google: google_id}]